--[[
    HEIST CREW — KenneyPalette (GENERATED, do not hand-edit)
    ────────────────────────────────────────────────
    The Kenney furniture-kit ships NO texture images. It colours models with
    named flat materials defined as RGB in the .mtl files, and Roblox's FBX
    importer drops those — every piece arrives white. (Confirmed 2026-09-22:
    Malachi imported desk.fbx and got a white desk.)

    This table restores them. Generated by tools/gen_palette.py, which parses
    all 140 .mtl files for their real Kd values and COUNTS FACES per material
    in the matching .obj, so "dominant" is measured rather than assumed.

    The dungeon and factory kits do NOT need this — they ship texture atlases
    and import with their colour intact.
--]]

local Palette = {}

-- Kenney material name -> { colour, Roblox Material }
Palette.MATERIALS = {
    _defaultMat    = { color = Color3.fromRGB(255, 255, 255), material = Enum.Material.SmoothPlastic },
    carpet         = { color = Color3.fromRGB(241,  94,  87), material = Enum.Material.Fabric },
    carpetBlue     = { color = Color3.fromRGB( 91, 132, 221), material = Enum.Material.Fabric },
    carpetDarker   = { color = Color3.fromRGB(155,  76,  73), material = Enum.Material.Fabric },
    carpetWhite    = { color = Color3.fromRGB(248, 255, 255), material = Enum.Material.Fabric },
    fur            = { color = Color3.fromRGB(165, 117,  76), material = Enum.Material.Fabric },
    glass          = { color = Color3.fromRGB(178, 211, 196), material = Enum.Material.Glass },
    lamp           = { color = Color3.fromRGB(255, 233, 150), material = Enum.Material.Neon },
    metal          = { color = Color3.fromRGB(189, 210, 214), material = Enum.Material.Metal },
    metalDark      = { color = Color3.fromRGB( 78,  99,  99), material = Enum.Material.Metal },
    metalLight     = { color = Color3.fromRGB(239, 250, 244), material = Enum.Material.Metal },
    metalMedium    = { color = Color3.fromRGB( 94, 119, 119), material = Enum.Material.Metal },
    plant          = { color = Color3.fromRGB( 46, 209, 147), material = Enum.Material.Grass },
    wood           = { color = Color3.fromRGB(229, 153, 100), material = Enum.Material.Wood },
    woodDark       = { color = Color3.fromRGB(173, 116,  76), material = Enum.Material.Wood },
}

-- model name -> its dominant material (by face count)
Palette.MODELS = {
    ["bathroomCabinet"] = "wood",
    ["bathroomCabinetDrawer"] = "metalLight",
    ["bathroomMirror"] = "wood",
    ["bathroomSink"] = "_defaultMat",
    ["bathroomSinkSquare"] = "metalLight",
    ["bathtub"] = "carpetWhite",
    ["bear"] = "fur",
    ["bedBunk"] = "wood",
    ["bedDouble"] = "carpetWhite",
    ["bedSingle"] = "wood",
    ["bench"] = "wood",
    ["benchCushion"] = "wood",
    ["benchCushionLow"] = "wood",
    ["bookcaseClosed"] = "wood",
    ["bookcaseClosedDoors"] = "wood",
    ["bookcaseClosedWide"] = "wood",
    ["bookcaseOpen"] = "wood",
    ["bookcaseOpenLow"] = "wood",
    ["books"] = "carpetDarker",
    ["cabinetBed"] = "wood",
    ["cabinetBedDrawer"] = "wood",
    ["cabinetBedDrawerTable"] = "wood",
    ["cabinetTelevision"] = "wood",
    ["cabinetTelevisionDoors"] = "wood",
    ["cardboardBoxClosed"] = "wood",
    ["cardboardBoxOpen"] = "wood",
    ["ceilingFan"] = "metalLight",
    ["chair"] = "wood",
    ["chairCushion"] = "wood",
    ["chairDesk"] = "metalMedium",
    ["chairModernCushion"] = "metal",
    ["chairModernFrameCushion"] = "metal",
    ["chairRounded"] = "wood",
    ["coatRack"] = "wood",
    ["coatRackStanding"] = "wood",
    ["computerKeyboard"] = "metalDark",
    ["computerMouse"] = "metalDark",
    ["computerScreen"] = "metalDark",
    ["desk"] = "wood",
    ["deskCorner"] = "wood",
    ["doorway"] = "wood",
    ["doorwayFront"] = "metal",
    ["doorwayOpen"] = "wood",
    ["dryer"] = "metalLight",
    ["floorCorner"] = "wood",
    ["floorCornerRound"] = "wood",
    ["floorFull"] = "wood",
    ["floorHalf"] = "wood",
    ["hoodLarge"] = "metalDark",
    ["hoodModern"] = "metalMedium",
    ["kitchenBar"] = "wood",
    ["kitchenBarEnd"] = "wood",
    ["kitchenBlender"] = "glass",
    ["kitchenCabinet"] = "wood",
    ["kitchenCabinetCornerInner"] = "metal",
    ["kitchenCabinetCornerRound"] = "wood",
    ["kitchenCabinetDrawer"] = "wood",
    ["kitchenCabinetUpper"] = "wood",
    ["kitchenCabinetUpperCorner"] = "wood",
    ["kitchenCabinetUpperDouble"] = "wood",
    ["kitchenCabinetUpperLow"] = "wood",
    ["kitchenCoffeeMachine"] = "metalMedium",
    ["kitchenFridge"] = "metalLight",
    ["kitchenFridgeBuiltIn"] = "metalLight",
    ["kitchenFridgeLarge"] = "metalLight",
    ["kitchenFridgeSmall"] = "metalLight",
    ["kitchenMicrowave"] = "metalMedium",
    ["kitchenSink"] = "metalLight",
    ["kitchenStove"] = "metalDark",
    ["kitchenStoveElectric"] = "metalDark",
    ["lampRoundFloor"] = "lamp",
    ["lampRoundTable"] = "lamp",
    ["lampSquareCeiling"] = "lamp",
    ["lampSquareFloor"] = "lamp",
    ["lampSquareTable"] = "lamp",
    ["lampWall"] = "lamp",
    ["laptop"] = "metalDark",
    ["loungeChair"] = "carpet",
    ["loungeChairRelax"] = "carpet",
    ["loungeDesignChair"] = "carpetBlue",
    ["loungeDesignSofa"] = "carpetBlue",
    ["loungeDesignSofaCorner"] = "carpetBlue",
    ["loungeSofa"] = "carpet",
    ["loungeSofaCorner"] = "carpet",
    ["loungeSofaLong"] = "carpet",
    ["loungeSofaOttoman"] = "carpet",
    ["paneling"] = "wood",
    ["pillow"] = "carpet",
    ["pillowBlue"] = "carpetBlue",
    ["pillowBlueLong"] = "carpetBlue",
    ["pillowLong"] = "carpet",
    ["plantSmall1"] = "wood",
    ["plantSmall2"] = "plant",
    ["plantSmall3"] = "wood",
    ["pottedPlant"] = "wood",
    ["radio"] = "wood",
    ["rugDoormat"] = "wood",
    ["rugRectangle"] = "carpet",
    ["rugRound"] = "carpet",
    ["rugRounded"] = "carpet",
    ["rugSquare"] = "carpet",
    ["shower"] = "carpetWhite",
    ["showerRound"] = "carpetWhite",
    ["sideTable"] = "wood",
    ["sideTableDrawers"] = "wood",
    ["speaker"] = "metalMedium",
    ["speakerSmall"] = "metalMedium",
    ["stairs"] = "woodDark",
    ["stairsCorner"] = "woodDark",
    ["stairsOpen"] = "woodDark",
    ["stairsOpenSingle"] = "metal",
    ["stoolBar"] = "wood",
    ["stoolBarSquare"] = "wood",
    ["table"] = "wood",
    ["tableCloth"] = "wood",
    ["tableCoffee"] = "wood",
    ["tableCoffeeGlass"] = "metal",
    ["tableCoffeeGlassSquare"] = "metal",
    ["tableCoffeeSquare"] = "wood",
    ["tableCross"] = "wood",
    ["tableCrossCloth"] = "wood",
    ["tableGlass"] = "metal",
    ["tableRound"] = "wood",
    ["televisionAntenna"] = "metalMedium",
    ["televisionModern"] = "metalDark",
    ["televisionVintage"] = "metalDark",
    ["toaster"] = "metal",
    ["toilet"] = "carpetWhite",
    ["toiletSquare"] = "carpetWhite",
    ["trashcan"] = "metalDark",
    ["wall"] = "_defaultMat",
    ["wallCorner"] = "wood",
    ["wallCornerRond"] = "wood",
    ["wallDoorway"] = "wood",
    ["wallDoorwayWide"] = "wood",
    ["wallHalf"] = "_defaultMat",
    ["wallWindow"] = "wood",
    ["wallWindowSlide"] = "wood",
    ["washer"] = "metal",
    ["washerDryerStacked"] = "metal",
}

-- Tint an imported MeshPart to match the original Kenney colours.
-- Safe to call on anything: an unknown name is left untouched rather than
-- silently painted the wrong colour.
function Palette.apply(part, modelName)
    local matName = Palette.MODELS[modelName]
    if not matName then return false end
    local entry = Palette.MATERIALS[matName]
    if not entry then return false end
    part.Color = entry.color
    part.Material = entry.material
    return true
end

return Palette
