#!/usr/bin/env python3
"""
upload_kenney.py — upload Kenney .fbx models to Roblox via Open Cloud, record the asset ids.

WHY
    Roblox can't load a model from a file on disk — every mesh has to live on Roblox as an
    asset first. Doing that by hand is Studio's 3D Importer, one model at a time, ~300 times.
    This does it through the Open Cloud Assets API instead (POST /assets/v1/assets, which
    accepts .fbx as assetType "Model" — verified against create.roblox.com docs 2026-09-24).

WHAT IT TOUCHES
    • Reads   src/assets/_kenney/<pack>.zip            (the .fbx files, straight out of the zip)
    • Reads   ~/.claude/roblox-opencloud-key          (assets read+write key, never printed)
    • Creates Model assets on Roblox, owned by Soljaboi1919 (user 2501618318)
    • Writes  tools/kenney_assets.json                 (the ledger — source of truth)
    • Writes  src/shared/KenneyAssets.lua              (generated from the ledger, for the game)

WHAT IT WILL NEVER DO
    • Delete, overwrite, or re-upload an asset that's already in the ledger
    • Upload anything unless you pass --go (the default is a preview that changes nothing)
    • Touch any other part of the Roblox account — the key can't, and this doesn't ask

USAGE
    python3 tools/upload_kenney.py                         # preview: what would upload
    python3 tools/upload_kenney.py --go                    # upload furniture + factory
    python3 tools/upload_kenney.py --go --kits factory     # just one kit
    python3 tools/upload_kenney.py --go --only desk,chair  # just these models
    python3 tools/upload_kenney.py --regen                 # rebuild the .lua from the ledger
"""

import argparse
import json
import sys
import time
import zipfile
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
KENNEY = ROOT / "src" / "assets" / "_kenney"
LEDGER = ROOT / "tools" / "kenney_assets.json"
LUA_OUT = ROOT / "src" / "shared" / "KenneyAssets.lua"
KEY_FILE = Path.home() / ".claude" / "roblox-opencloud-key"
USER_ID = "2501618318"   # Soljaboi1919

API = "https://apis.roblox.com/assets/v1"

# kit name (as used in KenneyKit.SIZES) -> zip
PACKS = {
    "furniture": "kenney_furniture-kit.zip",
    "factory": "kenney_factory-kit_3.0.zip",
    "dungeon": "kenney_modular-dungeon-kit_1.0.zip",
}
DEFAULT_KITS = ["furniture", "factory"]   # dungeon is medieval-themed; opt in explicitly


def load_ledger():
    if LEDGER.exists():
        return json.loads(LEDGER.read_text())
    return {}


def save_ledger(ledger):
    LEDGER.write_text(json.dumps(dict(sorted(ledger.items())), indent=2) + "\n", newline="\r\n")


def write_lua(ledger):
    lines = [
        "--[[",
        "    HEIST CREW — KenneyAssets (GENERATED by tools/upload_kenney.py — do not hand-edit)",
        "    Roblox asset ids for the Kenney models uploaded via Open Cloud.",
        "    Load one with InsertService:LoadAsset(id), then size it with KenneyKit.applySize.",
        "--]]",
        "",
        "local KenneyAssets = {",
    ]
    by_kit = {}
    for key, entry in ledger.items():
        kit, name = key.split("/", 1)
        by_kit.setdefault(kit, {})[name] = entry["assetId"]
    for kit in sorted(by_kit):
        lines.append(f"    {kit} = {{")
        for name in sorted(by_kit[kit]):
            lines.append(f'        ["{name}"] = {by_kit[kit][name]},')
        lines.append("    },")
    lines += ["}", "", "return KenneyAssets", ""]
    LUA_OUT.write_text("\n".join(lines), newline="\r\n")


def fbx_members(kit):
    z = zipfile.ZipFile(KENNEY / PACKS[kit])
    for info in z.infolist():
        n = info.filename
        if n.lower().endswith(".fbx") and "/FBX format/" in n:
            yield z, info, Path(n).stem


def upload_one(key, kit, name, data):
    body = {
        "assetType": "Model",
        "displayName": f"HC_{kit}_{name}"[:50],
        "description": f"Heist Crew - Kenney {kit} kit (CC0, kenney.nl)",
        "creationContext": {"creator": {"userId": USER_ID}},
    }
    for attempt in range(6):
        r = requests.post(
            f"{API}/assets",
            headers={"x-api-key": key},
            files={
                "request": (None, json.dumps(body), "application/json"),
                "fileContent": (f"{name}.fbx", data, "model/fbx"),
            },
            timeout=90,
        )
        if r.status_code == 429:
            wait = int(r.headers.get("Retry-After", 10 * (attempt + 1)))
            print(f"    rate limited, waiting {wait}s")
            time.sleep(wait)
            continue
        r.raise_for_status()
        op = r.json()["operationId"]
        break
    else:
        raise RuntimeError("gave up after repeated rate limits")

    for _ in range(40):
        time.sleep(3)
        r = requests.get(f"{API}/operations/{op}", headers={"x-api-key": key}, timeout=30)
        if r.status_code == 429:
            time.sleep(10)
            continue
        r.raise_for_status()
        j = r.json()
        if j.get("done"):
            resp = j.get("response") or {}
            if "assetId" not in resp:
                raise RuntimeError(f"operation finished without an asset: {j}")
            return resp["assetId"], (resp.get("moderationResult") or {}).get("moderationState")
    raise RuntimeError(f"operation {op} never finished")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--go", action="store_true", help="actually upload (default: preview)")
    ap.add_argument("--kits", default=",".join(DEFAULT_KITS))
    ap.add_argument("--only", default="", help="comma list of model names")
    ap.add_argument("--regen", action="store_true", help="just rebuild KenneyAssets.lua")
    args = ap.parse_args()

    ledger = load_ledger()
    if args.regen:
        write_lua(ledger)
        print(f"wrote {LUA_OUT.relative_to(ROOT)} ({len(ledger)} assets)")
        return

    kits = [k.strip() for k in args.kits.split(",") if k.strip()]
    for k in kits:
        if k not in PACKS:
            sys.exit(f"unknown kit '{k}' — expected one of {', '.join(PACKS)}")
    only = {n.strip() for n in args.only.split(",") if n.strip()}

    todo = []
    for kit in kits:
        for z, info, name in fbx_members(kit):
            if only and name not in only:
                continue
            key = f"{kit}/{name}"
            if key in ledger:
                continue
            if info.file_size > 20 * 1024 * 1024:
                print(f"  skip {key}: over the 20 MB upload limit")
                continue
            todo.append((z, info, kit, name, key))

    print(f"{len(ledger)} already uploaded, {len(todo)} to go ({', '.join(kits)})")
    if not args.go:
        for _, _, _, _, key in todo[:15]:
            print("  would upload", key)
        if len(todo) > 15:
            print(f"  ... and {len(todo) - 15} more")
        print("preview only — rerun with --go to upload")
        return

    key = KEY_FILE.read_text().strip()
    failed = []
    for i, (z, info, kit, name, lkey) in enumerate(todo, 1):
        try:
            asset_id, mod = upload_one(key, kit, name, z.read(info))
            ledger[lkey] = {"assetId": int(asset_id), "moderation": mod}
            save_ledger(ledger)   # after EVERY upload, so a crash never loses ids
            print(f"[{i}/{len(todo)}] {lkey} -> {asset_id} ({mod})", flush=True)
        except Exception as e:  # keep going; report at the end
            failed.append((lkey, str(e)[:200]))
            print(f"[{i}/{len(todo)}] {lkey} FAILED: {str(e)[:200]}", flush=True)
        time.sleep(1)

    write_lua(ledger)
    print(f"done: {len(ledger)} in ledger, {len(failed)} failed")
    for k, e in failed:
        print("  FAILED", k, e)


if __name__ == "__main__":
    main()
